package com.jaiva;

import com.jaiva.interpreter.libs.BaseLibrary;
import com.jaiva.interpreter.runtime.IConfig;

import java.lang.reflect.Constructor;

public final class Plugin {

    private Plugin() {
    }

    /**
     * Loads and instantiates a Jaiva external library using the classloader
     * which loaded this class, then generates its tooling JSON.
     *
     * <p>This method is intended to be invoked by external tooling such as
     * the Jaiva Maven plugin.</p>
     *
     * @param className fully-qualified external library class name
     * @return tooling JSON generated by the library
     */
    public static String generateToolingJSON(String className) {
        try {
            Class<?> rawClass = Class.forName(
                    className,
                    true,
                    Plugin.class.getClassLoader()
            );

            Class<? extends BaseLibrary> libraryClass =
                    rawClass.asSubclass(BaseLibrary.class);

            IConfig<Object> config = new IConfig<>(null);

            BaseLibrary library = instantiate(libraryClass, config);

            return BaseLibrary.toolingJSONof(library);

        } catch (Exception e) {
            throw new RuntimeException(
                    "Failed to generate tooling JSON for: " + className,
                    e
            );
        }
    }

    private static BaseLibrary instantiate(
            Class<? extends BaseLibrary> libraryClass,
            IConfig<Object> config
    ) throws Exception {

        try {
            Constructor<? extends BaseLibrary> constructor =
                    libraryClass.getDeclaredConstructor(IConfig.class);

            constructor.setAccessible(true);

            return constructor.newInstance(config);

        } catch (NoSuchMethodException ignored) {
            Constructor<? extends BaseLibrary> constructor =
                    libraryClass.getDeclaredConstructor();

            constructor.setAccessible(true);

            return constructor.newInstance();
        }
    }
}