package com.jaiva;

import com.jaiva.interpreter.libs.BaseLibrary;
import com.jaiva.interpreter.libs.LibraryLike;
import com.jaiva.interpreter.libs.global.Globals;
import com.jaiva.interpreter.runtime.IConfig;

public final class Plugin {

    private Plugin() {
    }

    /**
     * Loads and instantiates a Jaiva external library using the classloader
     * which loaded this class, then generates its tooling JSON.
     *
     * <p>This method is intended to be invoked by external tooling such as
     * the Jaiva Maven plugin.</p>
     *
     * @param className fully-qualified external library class name
     * @return tooling JSON generated by the library
     */
    public static String generateToolingJSON(String className) {
        try {
            Class<?> rawClass = Class.forName(
                    className,
                    true,
                    Plugin.class.getClassLoader()
            );

            Class<? extends BaseLibrary> libraryClass =
                    rawClass.asSubclass(BaseLibrary.class);


            BaseLibrary.externalLibraryRequirements(libraryClass);

            IConfig<Object> config = new IConfig<>(null);

            Globals globals = new Globals(config);

            LibraryLike lib = LibraryLike.of(libraryClass);

            BaseLibrary library = lib.loadClassLibrary(config, globals);

            return library.toToolingJSON();

        } catch (Exception e) {
            throw new RuntimeException(
                    "Failed to generate tooling JSON for: " + className,
                    e
            );
        }
    }

}