<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.jaiva</groupId>
        <artifactId>jaiva-parent</artifactId>
        <version>6.0.0-beta.6</version>
    </parent>

    <artifactId>core</artifactId>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>

        <!-- For tests -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.9.3</version>
            <scope>test</scope>
        </dependency>

        <!-- My custom common utilities. Such as tuples and more function arities-->

        <dependency>
            <groupId>com.github.yetnt</groupId>
            <artifactId>ytils</artifactId>
            <version>1.0.1</version>
        </dependency>

        <!-- Specifically for loading internal jaiva libraries so we don't have to define it everytime -->

        <dependency>
            <groupId>io.github.classgraph</groupId>
            <artifactId>classgraph</artifactId>
            <version>4.8.180</version>
        </dependency>

    </dependencies>

    <profiles>
        <profile>
            <id>release-cli</id>
            <build>
                <plugins>

                    <plugin>
                        <artifactId>maven-antrun-plugin</artifactId>
                        <version>3.1.0</version>

                        <executions>
                            <execution>
                                <id>prepare-cli</id>
                                <phase>package</phase>

                                <goals>
                                    <goal>run</goal>
                                </goals>

                                <configuration>
                                    <target>

                                        <delete file="${project.basedir}/jaiva-cli/jaiva.jar"/>
                                        <delete file="${project.basedir}/jaiva-cli/jaiva-sources.jar"/>
                                        <delete file="${project.basedir}/jaiva-cli/jaiva.zip"/>

                                        <copy
                                                file="${project.build.directory}/${project.artifactId}-${project.version}.jar"
                                                tofile="${project.basedir}/jaiva-cli/jaiva.jar"/>

                                        <copy
                                                file="${project.build.directory}/${project.artifactId}-${project.version}-sources.jar"
                                                tofile="${project.basedir}/jaiva-cli/jaiva-sources.jar"/>

                                        <echo file="${project.basedir}/jaiva-cli/version">
                                            ${project.version}
                                        </echo>

                                        <zip
                                                destfile="${project.basedir}/jaiva-cli/jaiva.zip"
                                                basedir="${project.basedir}/jaiva-cli">

                                            <exclude name="jaiva.zip"/>

                                        </zip>

                                    </target>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>

                </plugins>
            </build>
        </profile>
    </profiles>

    <build>

        <pluginManagement>
            <!--
            <plugins>
                <plugin>
                    <groupId>org.panteleyev</groupId>
                    <artifactId>jpackage-maven-plugin</artifactId>
                    <version>1.6.0</version>
                    <configuration>
                        <name>Jaiva</name>
                    </configuration>
                </plugin>
            </plugins>
            -->
        </pluginManagement>

        <plugins>

            <!--
                Creates the actual executable Jaiva JAR.

                This bundles Jaiva's runtime dependencies (currently ytils)
                into the JAR itself.

                It does NOT bundle the Java runtime.
            -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.0</version>

                <executions>
                    <execution>
                        <phase>package</phase>

                        <goals>
                            <goal>shade</goal>
                        </goals>

                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>

                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>com.jaiva.Main</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>

                <configuration>
                    <source>21</source>
                    <target>21</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.3.0</version>

                <executions>
                    <execution>
                        <id>attach-sources</id>

                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!--
            <plugin>
                <groupId>org.panteleyev</groupId>
                <artifactId>jpackage-maven-plugin</artifactId>
                <version>1.6.0</version>

                <executions>
                    <execution>
                        <phase>package</phase>

                        <goals>
                            <goal>jpackage</goal>
                        </goals>

                        <configuration>
                            <name>Jaiva</name>
                            <appVersion>${project.version}</appVersion>
                            <icon>src/main/resources/jaiva.ico</icon>
                            <description>Jaiva! Tokenizer &amp; Interpreter</description>
                            <vendor>yetnt</vendor>
                            <mainClass>com.jaiva.Main</mainClass>
                            <mainJar>${project.build.finalName}.jar</mainJar>
                            <resourceDir>src/main/resources</resourceDir>
                            <type>MSI</type>
                            <winConsole>true</winConsole>
                            <installDir></installDir>

                            <input>${project.build.directory}</input>
                            <destination>${project.build.directory}/jpackage</destination>

                            <fileAssociations>
                                <fileAssociation>src/main/resources/file-assoc-jaiva.properties</fileAssociation>
                                <fileAssociation>src/main/resources/file-assoc-jva.properties</fileAssociation>
                                <fileAssociation>src/main/resources/file-assoc-jiv.properties</fileAssociation>
                            </fileAssociations>

                            <winPerUserInstall>false</winPerUserInstall>
                            <aboutUrl>https://github.com/yetnt/jaiva</aboutUrl>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            -->

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.3.1</version>

                <executions>
                    <execution>
                        <id>copy-icon</id>
                        <phase>process-resources</phase>

                        <goals>
                            <goal>copy-resources</goal>
                        </goals>

                        <configuration>
                            <outputDirectory>${project.build.directory}</outputDirectory>

                            <resources>
                                <resource>
                                    <directory>src/main/resources</directory>

                                    <includes>
                                        <include>jaiva.ico</include>
                                    </includes>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>

</project>